### ISSUE TITLE
Field to specify minimum version of the Nirum compiler

### ISSUE THREAD

**Issue by dahlia** [spoqa/nirum#237]
A Nirum package may use recently introduced features of the compiler so that it requires the minimum version of the compiler.  Although it could be achieved by simply adding a new field to *package.toml* manifest:

```toml
version = "1.0.0"
compiler_requires = ">= 0.3.0"
```

The syntax also could be unified to #26:

```toml
version = "1.0.0"

[dependencies]
"http://nirum.org/" = ">= 0.3.0"
```
